# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:11.0
        working_directory: ~/repo
        steps:
            # build holoflows-kit
            - run: |
                  cd ..
                  git clone -q --depth=1 https://github.com/DimensionFoundation/holoflows-kit
            - restore_cache:
                  keys:
                      - v1-dependencies-holoflows-{{ checksum "~/holoflows-kit/package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-holoflows-
            - run: |
                  cd ../holoflows-kit
                  yarn install
            - save_cache:
                  paths:
                      - ~/holoflows-kit/node_modules
                  key: v1-dependencies-holoflows-{{ checksum "~/holoflows-kit/package.json" }}
            - run: |
                  cd ../holoflows-kit
                  yarn build
                  yarn link

            # build maskbook
            - checkout
            - restore_cache:
                  keys:
                      - tsbuild-cache
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-
            - run: yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn link @holoflows/kit
            - run: yarn build
            - run: sudo apt-get install zip
            - save_cache:
                  paths:
                      - .tscache/
                  key: tsbuild-cache
            - run: zip -r Maskbook.zip build/
            - store_artifacts:
                  path: Maskbook.zip
            - persist_to_workspace:
                  path: ~/repo/
                  paths:
                      - Maskbook.zip
    publish-github-release:
        docker:
            - image: cibuilds/github:0.10
        steps:
            - attach_workspace:
                  at: ~/repo/
            - run:
                  name: 'Publish Release on GitHub'
                  command: |
                      ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} --replace ~/repo/Maskbook.zip

workflows:
    version: 2
    main:
        jobs:
            - build
            - publish-github-release:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - released
